server.port=8443
server.ssl.enabled=true
server.ssl.key-store=/opt/certs/spring.p12
server.ssl.key-store-password=SpringSecure123
server.ssl.key-store-type=PKCS12
spring.datasource.url=jdbc:h2:file:./data/securedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=false
spring.main.allow-circular-references=true
