server.port=8443

# Ajusta estos valores cuando tengas el certificado emitido por Let's Encrypt
server.ssl.enabled=true
server.ssl.key-store=/opt/certs/spring-backend.p12
server.ssl.key-store-password=ChangeThisPassword
server.ssl.key-store-type=PKCS12

spring.datasource.url=jdbc:h2:file:./data/securedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=false
